language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.npm"
matrix:
  fast_finish: true
  include:
    - env:
      before_script:
        - npm install
      script:
        - npm test
        - npm run build
